version: '3'

services:
  php:
    image: php7.2-apache-trial2
    volumes:
      - ./html:/var/www/html
    ports:
      - 8000:80
    container_name: php7.2-trial2
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql # Composefileからみた相対パス
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql5.7-trial2
